# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ofstd_tests dcm2xml dcmconv dcmcrle dcmdrle dcmdump dcmftest dcmgpdir dump2dcm xml2dcm pdf2dcm dcm2pdf img2dcm dcm2json dcmodify dcmdata_tests dcmdspfn dcod2lum dconvlum dcm2pnm dcmquant dcmscale dcmcjpeg dcmdjpeg dcmj2pnm dcmmkdir dcmcjpls dcmdjpls dcml2pnm dcmrecv dcmsend echoscu findscu getscu movescu storescp storescu termscu dcmnet_tests dsr2html dsr2xml dsrdump xml2dsr mkreport dcmsr_tests dcmsign wlmscpfs dcmqrscp dcmqridx dcmqrti dcmmkcrv dcmmklut dcmp2pgm dcmprscp dcmprscu dcmpschk dcmpsmk dcmpsprt dcmpsrcv dcmpssnd drtdump drttest dcmrt_tests dcmiod_tests dcmseg_tests ofstd oflog dcmdata i2d dcmimgle dcmimage dcmjpeg ijg8 ijg12 ijg16 dcmjpls charls dcmtls dcmnet dcmsr cmr dcmdsig dcmwlm dcmqrdb dcmpstat dcmrt dcmiod dcmfg dcmseg dcmtract dcmpmap)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ofstd_tests
add_executable(ofstd_tests IMPORTED)

# Create imported target dcm2xml
add_executable(dcm2xml IMPORTED)

# Create imported target dcmconv
add_executable(dcmconv IMPORTED)

# Create imported target dcmcrle
add_executable(dcmcrle IMPORTED)

# Create imported target dcmdrle
add_executable(dcmdrle IMPORTED)

# Create imported target dcmdump
add_executable(dcmdump IMPORTED)

# Create imported target dcmftest
add_executable(dcmftest IMPORTED)

# Create imported target dcmgpdir
add_executable(dcmgpdir IMPORTED)

# Create imported target dump2dcm
add_executable(dump2dcm IMPORTED)

# Create imported target xml2dcm
add_executable(xml2dcm IMPORTED)

# Create imported target pdf2dcm
add_executable(pdf2dcm IMPORTED)

# Create imported target dcm2pdf
add_executable(dcm2pdf IMPORTED)

# Create imported target img2dcm
add_executable(img2dcm IMPORTED)

# Create imported target dcm2json
add_executable(dcm2json IMPORTED)

# Create imported target dcmodify
add_executable(dcmodify IMPORTED)

# Create imported target dcmdata_tests
add_executable(dcmdata_tests IMPORTED)

# Create imported target dcmdspfn
add_executable(dcmdspfn IMPORTED)

# Create imported target dcod2lum
add_executable(dcod2lum IMPORTED)

# Create imported target dconvlum
add_executable(dconvlum IMPORTED)

# Create imported target dcm2pnm
add_executable(dcm2pnm IMPORTED)

# Create imported target dcmquant
add_executable(dcmquant IMPORTED)

# Create imported target dcmscale
add_executable(dcmscale IMPORTED)

# Create imported target dcmcjpeg
add_executable(dcmcjpeg IMPORTED)

# Create imported target dcmdjpeg
add_executable(dcmdjpeg IMPORTED)

# Create imported target dcmj2pnm
add_executable(dcmj2pnm IMPORTED)

# Create imported target dcmmkdir
add_executable(dcmmkdir IMPORTED)

# Create imported target dcmcjpls
add_executable(dcmcjpls IMPORTED)

# Create imported target dcmdjpls
add_executable(dcmdjpls IMPORTED)

# Create imported target dcml2pnm
add_executable(dcml2pnm IMPORTED)

# Create imported target dcmrecv
add_executable(dcmrecv IMPORTED)

# Create imported target dcmsend
add_executable(dcmsend IMPORTED)

# Create imported target echoscu
add_executable(echoscu IMPORTED)

# Create imported target findscu
add_executable(findscu IMPORTED)

# Create imported target getscu
add_executable(getscu IMPORTED)

# Create imported target movescu
add_executable(movescu IMPORTED)

# Create imported target storescp
add_executable(storescp IMPORTED)

# Create imported target storescu
add_executable(storescu IMPORTED)

# Create imported target termscu
add_executable(termscu IMPORTED)

# Create imported target dcmnet_tests
add_executable(dcmnet_tests IMPORTED)

# Create imported target dsr2html
add_executable(dsr2html IMPORTED)

# Create imported target dsr2xml
add_executable(dsr2xml IMPORTED)

# Create imported target dsrdump
add_executable(dsrdump IMPORTED)

# Create imported target xml2dsr
add_executable(xml2dsr IMPORTED)

# Create imported target mkreport
add_executable(mkreport IMPORTED)

# Create imported target dcmsr_tests
add_executable(dcmsr_tests IMPORTED)

# Create imported target dcmsign
add_executable(dcmsign IMPORTED)

# Create imported target wlmscpfs
add_executable(wlmscpfs IMPORTED)

# Create imported target dcmqrscp
add_executable(dcmqrscp IMPORTED)

# Create imported target dcmqridx
add_executable(dcmqridx IMPORTED)

# Create imported target dcmqrti
add_executable(dcmqrti IMPORTED)

# Create imported target dcmmkcrv
add_executable(dcmmkcrv IMPORTED)

# Create imported target dcmmklut
add_executable(dcmmklut IMPORTED)

# Create imported target dcmp2pgm
add_executable(dcmp2pgm IMPORTED)

# Create imported target dcmprscp
add_executable(dcmprscp IMPORTED)

# Create imported target dcmprscu
add_executable(dcmprscu IMPORTED)

# Create imported target dcmpschk
add_executable(dcmpschk IMPORTED)

# Create imported target dcmpsmk
add_executable(dcmpsmk IMPORTED)

# Create imported target dcmpsprt
add_executable(dcmpsprt IMPORTED)

# Create imported target dcmpsrcv
add_executable(dcmpsrcv IMPORTED)

# Create imported target dcmpssnd
add_executable(dcmpssnd IMPORTED)

# Create imported target drtdump
add_executable(drtdump IMPORTED)

# Create imported target drttest
add_executable(drttest IMPORTED)

# Create imported target dcmrt_tests
add_executable(dcmrt_tests IMPORTED)

# Create imported target dcmiod_tests
add_executable(dcmiod_tests IMPORTED)

# Create imported target dcmseg_tests
add_executable(dcmseg_tests IMPORTED)

# Create imported target ofstd
add_library(ofstd STATIC IMPORTED)

# Create imported target oflog
add_library(oflog STATIC IMPORTED)

# Create imported target dcmdata
add_library(dcmdata STATIC IMPORTED)

# Create imported target i2d
add_library(i2d STATIC IMPORTED)

# Create imported target dcmimgle
add_library(dcmimgle STATIC IMPORTED)

# Create imported target dcmimage
add_library(dcmimage STATIC IMPORTED)

# Create imported target dcmjpeg
add_library(dcmjpeg STATIC IMPORTED)

# Create imported target ijg8
add_library(ijg8 STATIC IMPORTED)

# Create imported target ijg12
add_library(ijg12 STATIC IMPORTED)

# Create imported target ijg16
add_library(ijg16 STATIC IMPORTED)

# Create imported target dcmjpls
add_library(dcmjpls STATIC IMPORTED)

# Create imported target charls
add_library(charls STATIC IMPORTED)

# Create imported target dcmtls
add_library(dcmtls STATIC IMPORTED)

# Create imported target dcmnet
add_library(dcmnet STATIC IMPORTED)

# Create imported target dcmsr
add_library(dcmsr STATIC IMPORTED)

# Create imported target cmr
add_library(cmr STATIC IMPORTED)

# Create imported target dcmdsig
add_library(dcmdsig STATIC IMPORTED)

# Create imported target dcmwlm
add_library(dcmwlm STATIC IMPORTED)

# Create imported target dcmqrdb
add_library(dcmqrdb STATIC IMPORTED)

# Create imported target dcmpstat
add_library(dcmpstat STATIC IMPORTED)

# Create imported target dcmrt
add_library(dcmrt STATIC IMPORTED)

# Create imported target dcmiod
add_library(dcmiod STATIC IMPORTED)

# Create imported target dcmfg
add_library(dcmfg STATIC IMPORTED)

# Create imported target dcmseg
add_library(dcmseg STATIC IMPORTED)

# Create imported target dcmtract
add_library(dcmtract STATIC IMPORTED)

# Create imported target dcmpmap
add_library(dcmpmap STATIC IMPORTED)

# Import target "ofstd_tests" for configuration "Release"
set_property(TARGET ofstd_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ofstd_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/ofstd_tests"
  )

# Import target "dcm2xml" for configuration "Release"
set_property(TARGET dcm2xml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcm2xml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcm2xml"
  )

# Import target "dcmconv" for configuration "Release"
set_property(TARGET dcmconv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmconv PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmconv"
  )

# Import target "dcmcrle" for configuration "Release"
set_property(TARGET dcmcrle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmcrle PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmcrle"
  )

# Import target "dcmdrle" for configuration "Release"
set_property(TARGET dcmdrle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdrle PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmdrle"
  )

# Import target "dcmdump" for configuration "Release"
set_property(TARGET dcmdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdump PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmdump"
  )

# Import target "dcmftest" for configuration "Release"
set_property(TARGET dcmftest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmftest PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmftest"
  )

# Import target "dcmgpdir" for configuration "Release"
set_property(TARGET dcmgpdir APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmgpdir PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmgpdir"
  )

# Import target "dump2dcm" for configuration "Release"
set_property(TARGET dump2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dump2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dump2dcm"
  )

# Import target "xml2dcm" for configuration "Release"
set_property(TARGET xml2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(xml2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/xml2dcm"
  )

# Import target "pdf2dcm" for configuration "Release"
set_property(TARGET pdf2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(pdf2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/pdf2dcm"
  )

# Import target "dcm2pdf" for configuration "Release"
set_property(TARGET dcm2pdf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcm2pdf PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcm2pdf"
  )

# Import target "img2dcm" for configuration "Release"
set_property(TARGET img2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(img2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/img2dcm"
  )

# Import target "dcm2json" for configuration "Release"
set_property(TARGET dcm2json APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcm2json PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcm2json"
  )

# Import target "dcmodify" for configuration "Release"
set_property(TARGET dcmodify APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmodify PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmodify"
  )

# Import target "dcmdata_tests" for configuration "Release"
set_property(TARGET dcmdata_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdata_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmdata_tests"
  )

# Import target "dcmdspfn" for configuration "Release"
set_property(TARGET dcmdspfn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdspfn PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmdspfn"
  )

# Import target "dcod2lum" for configuration "Release"
set_property(TARGET dcod2lum APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcod2lum PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcod2lum"
  )

# Import target "dconvlum" for configuration "Release"
set_property(TARGET dconvlum APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dconvlum PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dconvlum"
  )

# Import target "dcm2pnm" for configuration "Release"
set_property(TARGET dcm2pnm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcm2pnm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcm2pnm"
  )

# Import target "dcmquant" for configuration "Release"
set_property(TARGET dcmquant APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmquant PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmquant"
  )

# Import target "dcmscale" for configuration "Release"
set_property(TARGET dcmscale APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmscale PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmscale"
  )

# Import target "dcmcjpeg" for configuration "Release"
set_property(TARGET dcmcjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmcjpeg PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmcjpeg"
  )

# Import target "dcmdjpeg" for configuration "Release"
set_property(TARGET dcmdjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdjpeg PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmdjpeg"
  )

# Import target "dcmj2pnm" for configuration "Release"
set_property(TARGET dcmj2pnm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmj2pnm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmj2pnm"
  )

# Import target "dcmmkdir" for configuration "Release"
set_property(TARGET dcmmkdir APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmmkdir PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmmkdir"
  )

# Import target "dcmcjpls" for configuration "Release"
set_property(TARGET dcmcjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmcjpls PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmcjpls"
  )

# Import target "dcmdjpls" for configuration "Release"
set_property(TARGET dcmdjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdjpls PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmdjpls"
  )

# Import target "dcml2pnm" for configuration "Release"
set_property(TARGET dcml2pnm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcml2pnm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcml2pnm"
  )

# Import target "dcmrecv" for configuration "Release"
set_property(TARGET dcmrecv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmrecv PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmrecv"
  )

# Import target "dcmsend" for configuration "Release"
set_property(TARGET dcmsend APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmsend PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmsend"
  )

# Import target "echoscu" for configuration "Release"
set_property(TARGET echoscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(echoscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/echoscu"
  )

# Import target "findscu" for configuration "Release"
set_property(TARGET findscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(findscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/findscu"
  )

# Import target "getscu" for configuration "Release"
set_property(TARGET getscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(getscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/getscu"
  )

# Import target "movescu" for configuration "Release"
set_property(TARGET movescu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(movescu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/movescu"
  )

# Import target "storescp" for configuration "Release"
set_property(TARGET storescp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(storescp PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/storescp"
  )

# Import target "storescu" for configuration "Release"
set_property(TARGET storescu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(storescu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/storescu"
  )

# Import target "termscu" for configuration "Release"
set_property(TARGET termscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(termscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/termscu"
  )

# Import target "dcmnet_tests" for configuration "Release"
set_property(TARGET dcmnet_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmnet_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmnet_tests"
  )

# Import target "dsr2html" for configuration "Release"
set_property(TARGET dsr2html APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dsr2html PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dsr2html"
  )

# Import target "dsr2xml" for configuration "Release"
set_property(TARGET dsr2xml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dsr2xml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dsr2xml"
  )

# Import target "dsrdump" for configuration "Release"
set_property(TARGET dsrdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dsrdump PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dsrdump"
  )

# Import target "xml2dsr" for configuration "Release"
set_property(TARGET xml2dsr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(xml2dsr PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/xml2dsr"
  )

# Import target "mkreport" for configuration "Release"
set_property(TARGET mkreport APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mkreport PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/mkreport"
  )

# Import target "dcmsr_tests" for configuration "Release"
set_property(TARGET dcmsr_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmsr_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmsr_tests"
  )

# Import target "dcmsign" for configuration "Release"
set_property(TARGET dcmsign APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmsign PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmsign"
  )

# Import target "wlmscpfs" for configuration "Release"
set_property(TARGET wlmscpfs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(wlmscpfs PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/wlmscpfs"
  )

# Import target "dcmqrscp" for configuration "Release"
set_property(TARGET dcmqrscp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmqrscp PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmqrscp"
  )

# Import target "dcmqridx" for configuration "Release"
set_property(TARGET dcmqridx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmqridx PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmqridx"
  )

# Import target "dcmqrti" for configuration "Release"
set_property(TARGET dcmqrti APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmqrti PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmqrti"
  )

# Import target "dcmmkcrv" for configuration "Release"
set_property(TARGET dcmmkcrv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmmkcrv PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmmkcrv"
  )

# Import target "dcmmklut" for configuration "Release"
set_property(TARGET dcmmklut APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmmklut PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmmklut"
  )

# Import target "dcmp2pgm" for configuration "Release"
set_property(TARGET dcmp2pgm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmp2pgm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmp2pgm"
  )

# Import target "dcmprscp" for configuration "Release"
set_property(TARGET dcmprscp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmprscp PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmprscp"
  )

# Import target "dcmprscu" for configuration "Release"
set_property(TARGET dcmprscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmprscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmprscu"
  )

# Import target "dcmpschk" for configuration "Release"
set_property(TARGET dcmpschk APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpschk PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmpschk"
  )

# Import target "dcmpsmk" for configuration "Release"
set_property(TARGET dcmpsmk APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpsmk PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmpsmk"
  )

# Import target "dcmpsprt" for configuration "Release"
set_property(TARGET dcmpsprt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpsprt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmpsprt"
  )

# Import target "dcmpsrcv" for configuration "Release"
set_property(TARGET dcmpsrcv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpsrcv PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmpsrcv"
  )

# Import target "dcmpssnd" for configuration "Release"
set_property(TARGET dcmpssnd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpssnd PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmpssnd"
  )

# Import target "drtdump" for configuration "Release"
set_property(TARGET drtdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(drtdump PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/drtdump"
  )

# Import target "drttest" for configuration "Release"
set_property(TARGET drttest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(drttest PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/drttest"
  )

# Import target "dcmrt_tests" for configuration "Release"
set_property(TARGET dcmrt_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmrt_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmrt_tests"
  )

# Import target "dcmiod_tests" for configuration "Release"
set_property(TARGET dcmiod_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmiod_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmiod_tests"
  )

# Import target "dcmseg_tests" for configuration "Release"
set_property(TARGET dcmseg_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmseg_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/bin/dcmseg_tests"
  )

# Import target "ofstd" for configuration "Release"
set_property(TARGET ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ofstd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/lib/x86_64-linux-gnu/libicuuc.so;pthread"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libofstd.a"
  )

# Import target "oflog" for configuration "Release"
set_property(TARGET oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(oflog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/liboflog.a"
  )

# Import target "dcmdata" for configuration "Release"
set_property(TARGET dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdata PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;/usr/lib/x86_64-linux-gnu/libz.so"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmdata.a"
  )

# Import target "i2d" for configuration "Release"
set_property(TARGET i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(i2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmdata"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libi2d.a"
  )

# Import target "dcmimgle" for configuration "Release"
set_property(TARGET dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmimgle PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmimgle.a"
  )

# Import target "dcmimage" for configuration "Release"
set_property(TARGET dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmimage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "oflog;dcmdata;dcmimgle;/usr/lib/x86_64-linux-gnu/libtiff.so;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/x86_64-linux-gnu/libpng.so"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmimage.a"
  )

# Import target "dcmjpeg" for configuration "Release"
set_property(TARGET dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage;ijg8;ijg12;ijg16"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmjpeg.a"
  )

# Import target "ijg8" for configuration "Release"
set_property(TARGET ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ijg8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libijg8.a"
  )

# Import target "ijg12" for configuration "Release"
set_property(TARGET ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ijg12 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libijg12.a"
  )

# Import target "ijg16" for configuration "Release"
set_property(TARGET ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ijg16 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libijg16.a"
  )

# Import target "dcmjpls" for configuration "Release"
set_property(TARGET dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmjpls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage;charls"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmjpls.a"
  )

# Import target "charls" for configuration "Release"
set_property(TARGET charls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(charls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libcharls.a"
  )

# Import target "dcmtls" for configuration "Release"
set_property(TARGET dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmtls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata;dcmnet;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmtls.a"
  )

# Import target "dcmnet" for configuration "Release"
set_property(TARGET dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmnet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;/usr/lib/x86_64-linux-gnu/libwrap.so"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmnet.a"
  )

# Import target "dcmsr" for configuration "Release"
set_property(TARGET dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmsr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage;/usr/lib/x86_64-linux-gnu/libxml2.so"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmsr.a"
  )

# Import target "cmr" for configuration "Release"
set_property(TARGET cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cmr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmsr"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libcmr.a"
  )

# Import target "dcmdsig" for configuration "Release"
set_property(TARGET dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdsig PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmdsig.a"
  )

# Import target "dcmwlm" for configuration "Release"
set_property(TARGET dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmwlm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmwlm.a"
  )

# Import target "dcmqrdb" for configuration "Release"
set_property(TARGET dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmqrdb PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmqrdb.a"
  )

# Import target "dcmpstat" for configuration "Release"
set_property(TARGET dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpstat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage;dcmnet;dcmdsig;dcmtls;dcmsr;dcmqrdb"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmpstat.a"
  )

# Import target "dcmrt" for configuration "Release"
set_property(TARGET dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmrt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmrt.a"
  )

# Import target "dcmiod" for configuration "Release"
set_property(TARGET dcmiod APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmiod PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmdata;ofstd;oflog"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmiod.a"
  )

# Import target "dcmfg" for configuration "Release"
set_property(TARGET dcmfg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmfg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmiod;dcmdata;ofstd;oflog"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmfg.a"
  )

# Import target "dcmseg" for configuration "Release"
set_property(TARGET dcmseg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmseg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmfg;dcmiod;dcmdata;ofstd;oflog"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmseg.a"
  )

# Import target "dcmtract" for configuration "Release"
set_property(TARGET dcmtract APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmtract PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmiod;dcmdata;ofstd;oflog"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmtract.a"
  )

# Import target "dcmpmap" for configuration "Release"
set_property(TARGET dcmpmap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpmap PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmfg;dcmiod;dcmdata;ofstd;oflog"
  IMPORTED_LOCATION_RELEASE "/home/sabsr3/ECIQC/dcmtk-3.6.1_20170228/lib/libdcmpmap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
