name: "Unit tests: Coverage"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Unit test coverage
    runs-on: ubuntu-20.04

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: update sudo apt 
        run: sudo apt-get update 
        
      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh
      
      - name: install tools
        run: sudo apt install g++-10 lcov libcurl4-openssl-dev

      - name: make build directory
        run: mkdir build_dir

      - name: run unit tests with coverage
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_COVERAGE=ON
          cmake --build . --parallel 2 --target unit_tests
          ctest -j2 --output-on-failure
        working-directory: build_dir
        env:
          CXX: g++-10

      - name: upload coverage results
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl https://codecov.io/bash) -f coverage.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODE_COV_TOKEN}}
        working-directory: build_dir
