
name: "Unit test coverage"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Unit test coverage
    runs-on: ubuntu-20.04

    steps:

      - name: checkout repo & vcpkg submodule
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-${{ hashFiles('scripts/vcpkg_dependencies') }}

      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: install tools
        run: sudo apt install g++-10 lcov libcurl4-openssl-dev

      - name: make build directory
        run: mkdir build_dir

      - name: run unit tests with coverage
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
          cmake --build . --parallel 2 --target unit_tests
          ctest -j2 --output-on-failure
        working-directory: build_dir
        env:
          CXX: g++-10

      - name: upload coverage results
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/vcpkg/*' '*/test/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl https://codecov.io/bash) -f coverage.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODE_COV_TOKEN}}
        working-directory: build_dir
