name: Sanitiser checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Sanitiser checks
    runs-on: macos-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
            bash scripts/install_dependencies_macosx.sh

      - name: install analysers
        run: brew install cppcheck

      - name: make build directories
        run: |
          mkdir address_san_dir
          mkdir leak_san_dir
          mkdir ub_san_dir
          mkdir thread_san_dir
          mkdir memory_san_dir
      - name: address sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_MEMCHECK=ON -DUSE_DCMTK_TARGETS=TRUE
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: address_san_dir
        env:
          CXX: clang++-10

      - name: leak sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_LEAK=ON -DUSE_DCMTK_TARGETS=TRUE
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: leak_san_dir
        env:
          CXX: clang++-10

      - name: undefined behaviour sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_UNDEFINED_BEHAVIOUR=ON -DUSE_DCMTK_TARGETS=TRUE
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: ub_san_dir
        env:
          CXX: clang++-10

      - name: thread sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_THREAD=ON -DUSE_DCMTK_TARGETS=TRUE
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: thread_san_dir
        env:
          CXX: clang++-10

      - name: memory sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_MEMORY=ON -DUSE_DCMTK_TARGETS=TRUE
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: memory_san_dir
        env:
          CXX: clang++-10
