name: Sanitiser checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Sanitiser checks
    runs-on: ubuntu-20.04

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: update sudo apt 
        run: sudo apt-get update 

      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh

      - name: install analysers
        run: sudo apt install g++-10

      - name: make build directories
        run: |
          mkdir address_san_dir
          mkdir leak_san_dir
          mkdir ub_san_dir
          mkdir thread_san_dir
          mkdir memory_san_dir
      - name: address sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_MEMCHECK=ON
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: address_san_dir
        env:
          CXX: g++-10

      - name: leak sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_LEAK=ON
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: leak_san_dir
        env:
          CXX: g++-10

      - name: undefined behaviour sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_UNDEFINED_BEHAVIOUR=ON
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: ub_san_dir
        env:
          CXX: g++-10

      - name: thread sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_THREAD=ON
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: thread_san_dir
        env:
          CXX: g++-10

      - name: memory sanitiser
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_SANITISER_MEMORY=ON
          cmake --build . --parallel 2 --target unit_tests
          ./unit_tests
        working-directory: memory_san_dir
        env:
          CXX: g++-10
