name: Static analysis checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Static analysis checks
    runs-on: ubuntu-20.04

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh

      - name: install analysers
        run: sudo apt install cppcheck clang-tidy-10

      - name: make build directories
        run: |
          mkdir cppcheck_dir
          mkdir clang_tidy_dir
      - name: compile with cppcheck
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_CPPCHECK=ON
          cmake --build . --parallel 2 --target qctool
        working-directory: cppcheck_dir
        env:
          CXX: clang++-10

      - name: compile with clang tidy
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DQCTool_ENABLE_CLANG_TIDY=ON
          cmake --build . --parallel 2 --target qctool
        working-directory: clang_tidy_dir
        env:
          CXX: clang++-10
