
name: "Unit tests: macOS"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  workflow_dispatch

jobs:

  build-and-test:
    name: Unit tests on macOS
    runs-on: macos-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
            bash scripts/install_dependencies_macosx.sh
      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target unit_tests
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 --output-on-failure
        working-directory: build_dir
